### ISSUE TITLE
Trying to set charge

### ISSUE THREAD

**Issue by christian-ek** [rthill/buderus#2]
Hi,
I am using your code from linux terminal and not in smarthome.
I successfully get data from my Bosch RC300 but when I try to set data I run into trouble.

I am trying to set "/dhwCircuits/dhw1/charge" to start but fails with 500.

Code:
```
    buderus = Buderus("xx", "xx")
    buderus._get_data("/dhwCircuits/dhw1/charge")
    buderus._set_data("/dhwCircuits/dhw1/charge", "start".encode('utf-8'))
```

```
DEBUG:__main__:Buderus fetching data from /dhwCircuits/dhw1/charge
DEBUG:__main__:Buderus data received from http://10.0.0.82/dhwCircuits/dhw1/charge: b'{"id":"/dhwCircuits/dhw1/charge","type":"stringValue","writeable":1,"recordable":0,"value":"stop","allowedValues":["stop","start"]}'
INFO:__main__:Buderus setting value for /dhwCircuits/dhw1/charge
ERROR:__main__:Buderus error happened at http://10.0.0.82/dhwCircuits/dhw1/charge: HTTP Error 500: Internal Server Error
```

Thankful if you have any pointers.

**Comment by rthill** [comment]
Hi,

I believe you have to add the value into a list. See _submit_data and _json_encode: https://github.com/smarthomeNG/plugins/blob/80e41af31ed53e405d5e89ed7091ffc4696c71d9/buderus/__init__.py#L126

**Comment by christian-ek** [comment]
Thank you for the reply. I tested it like this but still get 500 error. See anything wrong with my code?

```
    def _submit_data(self, id, value):
        self.logger.info("Buderus SETTING {} to {}".format(id, value))
        payload = self._json_encode(value)
        self.logger.debug(payload)
        req = self._set_data(id, self._encrypt(str(payload)))
```

 `bosch._submit_data("/dhwCircuits/dhw1/charge", "start")`


debug log:
```
INFO:__main__:Init Bosch
INFO:__main__:Buderus SETTING /dhwCircuits/dhw1/charge to start
DEBUG:__main__:[{"value": "start"}]
DEBUG:__main__:Buderus encrypted data: b"v\xb7\x8d\xe4M\x8c\xe4cm\xb8j\xf0\xbeB]\xa2\\{)A~\xd3a\x80\xb6\x0c4\x87'u\x8b0" -- Base64 encoded: b'dreN5E2M5GNtuGrwvkJdolx7KUF+02GAtgw0hyd1izA='
INFO:__main__:Buderus setting value for /dhwCircuits/dhw1/charge
ERROR:__main__:Buderus error happened at http://10.0.0.82/dhwCircuits/dhw1/charge: HTTP Error 500: Internal Server Error
```

**Comment by rthill** [comment]
Good question, as I can't test this myself. Did you check with their mobile application, is it possible to execute the requested action? You may also check the FHEM project if they have documented something.

**Comment by christian-ek** [comment]
In the application I am able to start hot water charge. Now I want to be able to do it via API and ultimately via google assistant.

![IMG_8A153A810564-1](https://user-images.githubusercontent.com/25098185/69637963-07ab7680-105a-11ea-88b2-63268bc69311.jpeg)

**Comment by rthill** [comment]
Sorry, I cannot help you with that. My best guess is to capture network traffic and decrypt the requests your mobile app is sending to the KM200.
